# RANDOM WALLETS MODE
IS_RANDOM_WALLETS = True  # True/False

# IF U NEED TO START YOUR BOT AFTERWHILE YOU CAN SET TRUE HERE AND CHOOSE TIME IN CONSOLE
IS_DELAYED_EXECUTION = True

IS_LOW_GAS = True

MAX_PRIORITY = 0.005
MAX_FEE = 0.005

# SLEEP MODE
IS_SLEEP = True  # True/False

SLEEP_FROM = 100
SLEEP_TO = 700

# GWEI CONTROL MODE
CHECK_GWEI = True
MAX_GWEI = 15

# RETRY MODE
RETRY_COUNT = 3

# CAIRO VERSION CONTROL
CAIRO_VERSION = 0

FEE_MULTIPLIER = 1.5

# DON'T CHANGE, WE NEED IT TO SWAP FROM ANY TOKEN TO ETH IF WE HAVE NOT ENOUGH ETH FOR NEXT ACTIONS
MIN_ETH_BALANCE = 0.0015