# RANDOM WALLETS MODE
IS_RANDOM_WALLETS = True  # True/False

# IF U NEED TO START YOUR BOT AFTERWHILE YOU CAN SET TRUE HERE AND CHOOSE TIME IN CONSOLE
IS_DELAYED_EXECUTION = True

# GWEI CONTROL MODE
CHECK_GWEI = True
MAX_GWEI = 15

# SLEEP MODE
IS_SLEEP = True  # True/False
SLEEP_FROM = 100
SLEEP_TO = 700

# IF U NEED LOW GAS MINT PRICE SET TRUE AND MAX_PRIORITY AND MAX_FEE WILL BE APPLIED
IS_LOW_GAS = True
MAX_PRIORITY = 0.005
MAX_FEE = 0.005

# RETRY MODE
RETRY_COUNT = 3

FEE_MULTIPLIER = 1.5

MINT_PRICE = (0.000001, 0.0001)
EDITION_SIZE = 1_000, 100000